spring:
  # datasource config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie_land
    username: root
    password: 1234
  # multipart config
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      location: C:\dev\project\movieland\src\main\resources\static\img
      max-file-size: 200MB
      max-request-size: 100MB

#mybatis config
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: kr.co.movieland.entity